[versions]
apollo = "4.0.0-rc.2"
kotlin = "2.0.0"

[libraries]
clikt = "com.github.ajalt.clikt:clikt:3.5.0"
serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.0"
apollo-tooling = { module = "com.apollographql.apollo:apollo-tooling", version.ref = "apollo" }
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.0"
okhttp = "com.squareup.okhttp3:okhttp:4.12.0"
jsonpathkt = "com.eygraber:jsonpathkt-kotlinx:3.0.2"
mordant = "com.github.ajalt.mordant:mordant:2.7.2"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
librarian = { id = "com.gradleup.librarian", version = "0.0.6" }